[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "NanoPolaris"
authors = [{name = "Paulo S. S. dos Santos", email = "paulo.s.santos@inesctec.pt"}]
dynamic = ["version", "description"]
